# -*- coding: utf-8 -*-
"""Ensembed_Sugarcane_image_Classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/ensembed-sugarcane-image-classifier-c125baeb-68a5-4964-bc84-5c8bc6eda32d.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250129/auto/storage/goog4_request%26X-Goog-Date%3D20250129T183055Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D7b7ab9f44121350f8760546162a6cd391b3c375e4d1b766e0fd69ba11c0174d92ec0b87218f4beab64b8658491adc4f8aae63a7d2ceaa810f8968a1c2b95f9864066dfb8a879209df081c7af78b97733b2632416293324a1aa968aa3bcfdb1b50a08114c016366537e17ab4c2eed53054f211668833b7143e78e7e5bdda7fafcaf7189857db86a06362d54bc6591b58946de2f54584cdd43307b108670e15d54b997ecc7b4954042cbed67534c39b337d461d6b5d9acde944207950616d5f1bf179e1de000e6733ab469637615664011e465449ffb3f542241fa2005fa5416025951ebc7750ac65d04508a50179888a93717070e3732816fda9a3b99e5bbda37
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

akilesh253_sugarcane_plant_diseases_dataset_path = kagglehub.dataset_download('akilesh253/sugarcane-plant-diseases-dataset')
saritham_sugarcane_vit_model_pytorch_default_1_path = kagglehub.model_download('saritham/sugarcane_vit_model/PyTorch/default/1')
saritham_swintransformer_sugarcane_pytorch_default_1_path = kagglehub.model_download('saritham/swintransformer_sugarcane/PyTorch/default/1')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

"""!pip install split-folders"""

!pip install split-folders

import splitfolders

input_folder = "/kaggle/input/sugarcane-plant-diseases-dataset/Sugarcane_leafs"
splitfolders.ratio(input_folder, output="/kaggle/working/sugarcanedisease", seed=42, ratio=(0.7, 0.15, 0.15), group_prefix=None)

"""1. Load the Pretrained Models"""

# Import standard libraries
import os
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

# PyTorch libraries
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Transformer models
from transformers import ViTForImageClassification, SwinForImageClassification

# Ensure reproducibility
torch.manual_seed(42)
np.random.seed(42)

# Set up device (GPU if available)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

# Check if CUDA is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

import torch
from transformers import ViTForImageClassification, SwinForImageClassification

# Paths to the saved model weights
vit_model_path = '/kaggle/input/sugarcane_vit_model/pytorch/default/1/vit_sugarcane_disease_detection.pth'
swin_model_path = '/kaggle/input/swintransformer_sugarcane/pytorch/default/1/swin_sugarcane_disease_detection.pth'

# Load ViT model
vit_model = ViTForImageClassification.from_pretrained(
    'google/vit-base-patch16-224-in21k',
    num_labels=6,  # Ensure num_labels is set correctly
    ignore_mismatched_sizes=True  # Add if necessary
)
vit_model.load_state_dict(torch.load(vit_model_path, map_location=device))
vit_model.to(device)
vit_model.eval()

# Load Swin Transformer model
swin_model = SwinForImageClassification.from_pretrained(
    'microsoft/swin-base-patch4-window7-224',
    num_labels=6,
    ignore_mismatched_sizes=True
)
swin_model.load_state_dict(torch.load(swin_model_path, map_location=device))
swin_model.to(device)
swin_model.eval()

import os
import torch
from torchvision import datasets, transforms

# Define data directories
data_dir = '/kaggle/working/sugarcanedisease'
train_dir = os.path.join(data_dir, 'train')
val_dir = os.path.join(data_dir, 'val')
test_dir = os.path.join(data_dir, 'test')

# Define image size and batch size
IMG_SIZE = (224, 224)
BATCH_SIZE = 16

# Define data transformations
# Corresponding to Keras ImageDataGenerator parameters
data_transforms = {
    'train': transforms.Compose([
        transforms.Resize(IMG_SIZE),
        transforms.RandomRotation(90),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.RandomAffine(degrees=0, scale=(0.8, 1.2)),
        transforms.ToTensor(),
        # No need for rescale=1./255 because ToTensor() does that
    ]),
    'val': transforms.Compose([
        transforms.Resize(IMG_SIZE),
        transforms.ToTensor(),
        # No need for rescale=1./255 because ToTensor() does that
    ]),
    'test': transforms.Compose([
        transforms.Resize(IMG_SIZE),
        transforms.ToTensor(),
        # No need for rescale=1./255 because ToTensor() does that
    ]),
}

# Create datasets using ImageFolder
train_dataset = datasets.ImageFolder(train_dir, transform=data_transforms['train'])
val_dataset = datasets.ImageFolder(val_dir, transform=data_transforms['val'])
test_dataset = datasets.ImageFolder(test_dir, transform=data_transforms['test'])

# Create DataLoaders
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=4)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=4)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=4)

import torch.nn.functional as F

def ensemble_predict(inputs):
    # Get outputs from ViT model
    vit_outputs = vit_model(inputs).logits  # Shape: [batch_size, num_classes]

    # Get outputs from Swin Transformer model
    swin_outputs = swin_model(inputs).logits  # Shape: [batch_size, num_classes]

    # Apply softmax to get probabilities
    vit_probs = F.softmax(vit_outputs, dim=1)
    swin_probs = F.softmax(swin_outputs, dim=1)

    # Average the probabilities
    avg_probs = (vit_probs + swin_probs) / 2

    # Get the final predictions
    _, ensemble_preds = torch.max(avg_probs, dim=1)

    return ensemble_preds, avg_probs

# Initialize counters
ensemble_correct = 0
total_samples = 0

# Keep track of all labels and predictions for metrics
all_labels = []
all_preds = []

model_outputs = []

# Evaluation loop
with torch.no_grad():
    for inputs, labels in tqdm(test_loader, desc='Evaluating Ensemble'):
        inputs = inputs.to(device)
        labels = labels.to(device)

        # Get ensemble predictions
        ensemble_preds, avg_probs = ensemble_predict(inputs)

        # Update counters
        ensemble_correct += (ensemble_preds == labels).sum().item()
        total_samples += labels.size(0)

        # Collect labels and predictions for metrics
        all_labels.extend(labels.cpu().numpy())
        all_preds.extend(ensemble_preds.cpu().numpy())
        model_outputs.extend(avg_probs.cpu().numpy())

# Calculate accuracy
ensemble_accuracy = ensemble_correct / total_samples
print(f'Ensemble Model Accuracy: {ensemble_accuracy:.4f}')

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# Generate classification report
report = classification_report(all_labels, all_preds, target_names=test_dataset.classes)
print(report)

# Compute confusion matrix
cm = confusion_matrix(all_labels, all_preds)

# Plot confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=test_dataset.classes,
            yticklabels=test_dataset.classes,
            cmap='Blues')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

def imshow(inp, title=None):
    """Show image for Tensor."""
    inp = inp.cpu().numpy().transpose((1, 2, 0))
    # Unnormalize
    inp = inp * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
    inp = np.clip(inp, 0, 1)
    plt.imshow(inp)
    if title:
        plt.title(title)
    plt.axis('off')

# Get a batch from the test loader
inputs, labels = next(iter(test_loader))
inputs = inputs.to(device)
labels = labels.to(device)

# Get individual and ensemble predictions
with torch.no_grad():
    # ViT predictions
    vit_outputs = vit_model(inputs).logits
    vit_probs = F.softmax(vit_outputs, dim=1)
    _, vit_preds = torch.max(vit_probs, dim=1)

    # Swin Transformer predictions
    swin_outputs = swin_model(inputs).logits
    swin_probs = F.softmax(swin_outputs, dim=1)
    _, swin_preds = torch.max(swin_probs, dim=1)

    # Ensemble predictions
    ensemble_preds, _ = ensemble_predict(inputs)

# Move data to CPU for visualization
inputs = inputs.cpu()
labels = labels.cpu()
vit_preds = vit_preds.cpu()
swin_preds = swin_preds.cpu()
ensemble_preds = ensemble_preds.cpu()

# Class names
class_names = test_dataset.classes

# Number of images to display
num_images = 6

# Plot the images with predictions
fig = plt.figure(figsize=(20, 5))
for idx in range(num_images):
    ax = fig.add_subplot(1, num_images, idx+1)
    imshow(inputs[idx])
    true_label = class_names[labels[idx]]
    vit_label = class_names[vit_preds[idx]]
    swin_label = class_names[swin_preds[idx]]
    ensemble_label = class_names[ensemble_preds[idx]]

    # Customize the title to show true and predicted labels
    ax.set_title(f'True: {true_label}\nViT: {vit_label}\nSwin: {swin_label}\nEnsemble: {ensemble_label}')
    ax.axis('off')
plt.tight_layout()
plt.show()

